basic:
  # 出战队伍的编号, 从0开始计数
  team_id: 3
  # 目标悬赏的编号, 从0开始计数
  boss_id: 5
  # 队伍中佣兵的数量，至少3人
  hero_count: 6
  # 完成悬赏后的奖励数目
  reward_count: 5
  # 在拿到神秘选项后是否提前结束战斗, 1 为提前结束, 0 为继续战斗
  early_stop: 1
  # 连续操作之间的延迟, 如果脚本经常少点某些按钮, 你可能需要增加延迟使delay > 1.0
  delay: 0.5
  # 屏幕上图像模板匹配的置信阈值
  confidence: 0.8
  # 战斗中佣兵的排序, 从0开始计数
  # 战斗开始时先上场的佣兵序号, 不是构筑队伍时的顺序,是战斗开始时在你手牌中的顺序
  start_heros_id: [0, 3, 4]
  # 如果任意场上佣兵阵亡, 替补佣兵的上场顺序
  next_heros_id: [5, 1, 2]



  # PVP投降脚本 或者 PVE
  mode: 'pve' # 'pvp' or 'pve'
  # 投降延迟时间
  pvp_delay: 0.5 # in seconds
  # 是否快速投降，因为官方的设置，有时候投降按钮位置会变化，快速投降会导致投降失败，
  fast_surrender: 0 # 1为快速投降，0为识别投降按钮再投降，当然投降速度会变慢
  # 如果界面卡住，最多等多久重启炉石
  longest_waiting: 60 # 秒计
  # 战网路径(注意路径要加双斜杠)
  battle_net_path: 'C:\\Program Files (x86)\\Battle.net\\Battle.net.exe'

skill:
  # battle round cycle
  # 战斗时技能每几回合循环一次
  cycle: 2
  # 战斗技能编号,从0开始
  ids:
    0: [0, 0, 0] # 第一回合使用的技能
    1: [0, 0, 1] # 第二回合使用的技能

    # 2: [0, 0, 0] # 第三回合使用的技能

  # 技能目标, 从0开始
  # -1 指点一下就能释放的无须瞄准的非指向性技能, 1 指中间的敌人
  targets:
    0: [1, -1, 1] # 第一回合的技能目标
    1: [1, -1, -1] # 第二回合的技能目标

    # 2: [1, 1, 1] # 第三回合的技能目标
    
  retry: 6

# coordinations of buttons etc.
location:
  # hero battle field locations
  heros: [ 677, 807, 943, 641 ] #  [first_x, mid_x, last_x, y]
  # hero skills locations
  skills: [ 653, 801, 963, 450 ] # [first_x, mid_x, last_x, y]
  # enemy battle field locations
  enemies: [ 677, 850, 943, 285 ] # [first_x, mid_x, last_x, y]

  # boss list locations
  boss: [ 405, 696, 916, 350, 667 ] # [first_x, mid_x, last_x, upper_y, lower_y]

  # treasures locations
  treasures: [ 707, 960, 1200, 376 ] # [first_x, mid_x, last_x, y]
  # treasure collection button
  treasures_collect: [ 968, 765 ] # [x, y]

  # visitors locations
  visitors: [ 545, 790, 1042, 420 ] # [first_x, mid_x, last_x, y]
  # visitor confirm button
  visitors_confirm: [ 791, 688 ] # [x, y]

  # heros on hand locations
  members: [ 622, 1000, 900 ] # [first_x, last_x, y]
  members_distance: 110
  # drag on hand hero to this location
  dragto: [ 1213, 564 ] # [x, y]

  # focus area before battle
  focus: [ 420, 650, 900, 453 ] # [first_x, mid_x, last_x, y]

  # final boss reward locations, depending on rewards count
  rewards:
    5: "(608, 706), (1034, 720), (1117, 371), (846, 311), (541, 430)" # [(x1, y1), ... ]
    4: "(660, 314), (554, 687), (1010, 794), (1117, 405)" # [(x1, y1), ... ]
    3: "(608, 706), (1034, 720), (1117, 371), (846, 311), (541, 430)" # [(x1, y1), ... ]
    # confirm button after reward collection
    confirm: [ 806, 525 ] #[x, y]

  # last boss location on map
  final_boss: [ 646, 227 ]
  # last confirm after finishing the map
  final_confirm: [ 794, 779 ]

  # empty location to click when waiting
  empty: [ 1488, 921 ]
  # empty location to click when waiting during battles
  empty_battle: [ 620, 750 ]
  # mouse location during scroll
  scroll: [ 1011, 764 ]
  # travel point confirm button
  travel: [ 1090, 674 ] #[x, y]
  # start point campfire on the map
  start_point: [ 646, 712 ] # [x, y]

  # team locations
  teams: [ 390, 600, 820, 330, 450, 600 ] # [first_x, mid_x, last_x, first_y, mid_y, last_y]
  # team select confirm button
  team_select: [ 1190, 800 ] # [x, y]
  # team lock button
  team_lock: [ 704, 572 ]

  # start game button, on boss selected or path selected
  start_game: [ 1250, 732 ] # [x, y]
  # start battle button, on skill selection finished
  start_battle: [ 1327, 454 ] # [x, y]

  # option button
  options: [ 1580, 920 ] # [x, y]
  # surrender button
  surrender: [ 815, 343 ] # [x, y]
  # view team members button
  view_team: [ 647, 885 ]
  # give up button
  give_up: [ 929, 706 ]
  # give up confirm button
  give_up_cfm: [ 712, 560 ]

  pvp_reward: [ 804, 471 ]


  #
  enemy_region: [ 400, 300, 1230, 400 ] # [x1, y1, x2, y2]
  hero_region: [ 400, 650, 1230, 750 ]