basic:
  # number of your team ID for battle, start counting from 0
  team_id: 3
  # number of the boss ID for battle, start counting from 0
  boss_id: 5
  # total number of your heros
  hero_count: 6
  # total number of rewards after finishing the map
  reward_count: 5
  # whether early stop battle once collected surprise option on map, 1 means early stop, 0 means continue
  early_stop: 0
  # delay between consecutive operations, if you always missing clicking some button, you may need to change the delay to > 1.0
  delay: 0.5
  # confidence threshold for image template matching on screen
  confidence: 0.8


  # PVP Surrender Mode or PVE
  mode: 'pve' # 'pvp' or 'pve'
  # When game started, after N seconds, start to surrender
  pvp_delay: 1.0 # in seconds
  # whether need fast surrender, since surrender button keeps changing position, fast surrender may fail to surrend
  fast_surrender: 1 # 1 means fast surrender, 0 means recognize surrender button first, which slows down surrrender speed
  # longest_waiting time to restart Hearthstone
  longest_waiting: 80 # second
  # Battle.net path
  bn_path: 'C:\\Program Files (x86)\\Battle.net\\Battle.net.exe'

  auto_restart: 0

heros:
  # First 3 heros' sequence number at start of the battle, it's sequence number of cards on hand, not in team buildup
  start_seq:
    [0, 1, 4]
  # Subsequent hero's sequence number
  sub_seq:
    [1, 2, 4]
  # Skill sequnce of all heros:
  # For example: 0:[2, 0, 1] means the first hero will cast its third skill, if cannot (like in cooldown) then cast first skill, if also in CD then cast second skill
  # Another example: 5:[0, 1, 2] means the sixth hero will cast its first skill, if cannot then cast its second skill, if also cannot then cast its third skill
  # The hero number should corresponds to numbers in start_seq
  # You should only care about heros in start_seq, the rest does not matter
  skill_priority:
    0: [1, 2, 0]
    1: [1, 2, 0]
    2: [1, 2, 0]
    3: [2, 1, 0]
    4: [0, 1, 2]
    5: [1, 0, 2]
    6: [1, 0, 2]
  # Basic damage of skills, currently leave it alone; but if you have any heros that can heal a target, then set that damage number to negative so that it will heal our side
  skill_basic_damage:
    0: [8, 8, 8]
    1: [8, 8, 8]
    2: [8, 8, 8]
    3: [8, 8, 8]
    4: [8, 8, 8]
    5: [8, 8, 8]
    6: [8, 8, 8]



retry:
  skill_selection: 6
  hero_selection: 6
  map_ready: 10

# coordinations of buttons etc.
location:
  # hero battle field locations
  heros: [ 410, 520, 630, 545 ] #  [first_x, mid_x, last_x, y]
  # hero skills locations
  skills: [ 390, 520, 650, 380 ] # [first_x, mid_x, last_x, y]
  skill_waiting: [ 100, 60 ]
  # enemy battle field locations
  enemies: [ 430, 550, 610, 240 ] # [first_x, mid_x, last_x, y]

  # boss list locations
  boss: [ 170, 400, 630, 300, 560 ] # [first_x, mid_x, last_x, upper_y, lower_y]

  # treasures locations
  treasures: [ 430, 650, 870, 390 ] # [first_x, mid_x, last_x, y]
  # treasure collection button
  treasures_collect: [ 650, 650 ] # [x, y]

  # visitors locations
  visitors: [ 290, 510, 720, 345 ] # [first_x, mid_x, last_x, y]
  # visitor confirm button
  visitors_confirm: [ 500, 564 ] # [x, y]

  # heros on hand locations
  members: [ 339, 706, 762 ] # [first_x, last_x, y]
  members_distance: 70
  # drag on hand hero to this location
  dragto: [ 780, 465 ] # [x, y]

  # focus area before battle
  focus: [ 165, 385, 600, 400 ] # [first_x, mid_x, last_x, y]

  # final boss reward locations, depending on rewards count
  rewards:
    5: "(547, 269), (294, 353), (367, 658), (739, 666), (805, 357)" # [(x1, y1), ... ]
    4: "(385, 257), (299, 588), (685, 685), (788, 342)" # [(x1, y1), ... ]
    3: "(555, 276), (340, 600), (787, 615)" # [(x1, y1), ... ]
    # confirm button after reward collection
    confirm: [ 535, 442 ] #[x, y]

  # last boss location on map
  final_boss: [ 380, 190 ]
  # last confirm after finishing the map
  final_confirm: [ 515, 660 ]

  # empty location to click when waiting
  empty: [ 937, 787 ]
  # empty location to click when waiting during battles
  empty_battle: [ 142, 324 ]
  # mouse location during scroll
  scroll: [ 682, 643 ]
  # travel point confirm button
  travel: [ 753, 573 ] #[x, y]
  # start point campfire on the map
  start_point: [ 377, 602 ] # [x, y]

  # team locations
  teams: [ 145, 338, 530, 277, 386, 500 ] # [first_x, mid_x, last_x, first_y, mid_y, last_y]
  # team select confirm button
  team_select: [ 838, 673 ] # [x, y]
  # team lock button
  team_lock: [ 438, 489 ]

  # start game button, on boss selected or path selected
  start_game: [ 908, 632 ] # [x, y]
  # start battle button, on skill selection finished
  start_battle: [ 925, 393 ] # [x, y]

  # option button
  options: [ 1007, 781 ] # [x, y]
  # surrender button
  surrender: [ 522, 303 ] # [x, y]
  # view team members button
  view_team: [ 393, 745 ]
  # give up button
  give_up: [ 613, 598 ]
  # give up confirm button
  give_up_cfm: [ 434, 464 ] # [x, y]



  #
  # Region of cards on Battlefield
  enemy_region: [ 200, 250, 888, 300 ] # [x1, y1, x2, y2]
  hero_region: [ 200, 560, 888, 610 ]
  hero_nready_region: [200, 470, 888, 520]
  offset: [15, 10]

