auto_restart: true
auto_tasks: false
bn_path: C:/Program Files (x86)/Battle.net/Battle.net.exe
boss_id: 5
confidence: 0.8
delay: 0.5
early_stop: false
hero:
  LETL_028H:
  - "\u62C9\u683C\u7EB3\u7F57\u65AF"
  - Ragnaros
  - 2, 3, 1
  - 0
  - 3
  LETL_030H:
  - "\u8FE6\u987F\u7537\u7235"
  - Baron Geddon
  - 2, 3, 1
  - 1
  - 1
  SWL_01H:
  - "\u5B89\u4E1C\u5C3C\u8FBE\u65AF"
  - Antonidas
  - 2, 1, 3
  - 2
  - 1
hs_path: C:/Program Files (x86)/Hearthstone/Hearthstone.exe
lang: ZH-1600x900
longest_waiting: 80
reward_count_dropdown: 'all'
screenshot_error: true
screenshot_reward: false
screenshot_treasure: false
screenshot_visitor: false
team_id: 1
ui_lang: chs
